.github/workflows/ci.yml, .github/workflows/golangci-lint.yml
Setting up some basic CI using Github Actions (linting and testing).
=> Setup basic CI

Makefile, cmd/rtcd/config.go, docs/project_structure.md, go.mod, go.sum, service/api/mux.go, service/auth.go, service/service.go, service/ws/config.go, service/ws/config_test.go, service/ws/conn.go, service/ws/msg.go, service/ws/option.go, service/ws/server.go, service/ws/server_test.go, service/ws/utils.go, service/ws/utils_test.go
PR implements a basic WebSocket server. It's not 100% complete but PR was getting larger so opted to send it now.
Some important things still missing:
- Documentation for exported methods and types.
- Connection timeout handler (ping-pong).
- More tests.
The API is rather simple, some highlights:
- Server implements the `http.Handler` to be easily hooked to the existing HTTP API server without need for coupling.
- Higher level won't be dealing with connections directly but through message passing (using connection ids).
- Two channels of communication, one to send and one to receive messages.
=> WebSocket server implementation

docs/project_structure.md, go.mod, go.sum, service/helper_test.go, service/service.go, service/ws/client.go, service/ws/client_test.go, service/ws/config.go, service/ws/config_test.go, service/ws/conn.go, service/ws/msg.go, service/ws/option.go, service/ws/server.go, service/ws/server_test.go, service/ws/utils.go
- Implemented WebSocket client.
- Added ping/pong support to server.
- Added some documentation.
This serves two main purposes:
- It makes testing the server easier and more complete.
- Client will be imported by the Calls plugin eventually when implementing the `plugin <-> rtcd` communication logic.
- Authentication service
- Connection management (at the service level)
=> WebSocket client implementation

.github/workflows/golangci-lint.yml, config/config.sample.toml, docs/project_structure.md, docs/security.md, go.mod, go.sum, service/auth.go, service/auth/crypto.go, service/auth/crypto_test.go, service/auth/service.go, service/auth/service_test.go, service/auth_test.go, service/config.go, service/helper_test.go, service/service.go, service/store/bitcask.go, service/store/store.go, service/store/store_test.go, service/version.go, service/ws/client.go
PR implements the main authentication logic for the service. Key points:
- We use an embedded persistent K/V store to save credentials. This may be temporary and I can see us moving to something centralized as the service evolves (e.g. multiple instances). We can support various store implementations behind a common interface based on the need.
- Implemented simple auth service to register and authenticate clients.
- Implemented WebSocket authentication handler using basic auth.
The expected authentication flow can be found in [docs/security.md](https://github.com/mattermost/rtcd/compare/auth?expand=1#diff-2c506cc756a5333f8fb5acb850d443980706602048f9ddb3dc515abacbfbce6a)
=> Auth implementation

go.mod, go.sum, service/perf/metrics.go, service/rtc/metrics.go, service/rtc/server.go, service/rtc/server_test.go, service/rtc/sfu.go, service/service.go
Just porting RTC related metrics from the plugin. https://github.com/mattermost/mattermost-plugin-calls/pull/40 has been updated as well.
=> Implement metrics

Makefile, build/Dockerfile
This introduces a multi-stage Dockerfile that builds the rtcd artifact.
https://mattermost.atlassian.net/browse/DOPS-917
=> Feature: Introduction of Dockerfile 

Makefile
Addition of Makefile target that takes care of building a docker image. 
Example : 
```
make docker-build tag=rtcd:latest
docker build -f build/Dockerfile . -t rtcd:latest
[+] Building 21.3s (15/15) FINISHED
=> [internal] load build definition from Dockerfile                                                                                               0.0s
=> => transferring dockerfile: 37B                                                                                                                0.0s
=> [internal] load .dockerignore                                                                                                                  0.0s
=> => transferring context: 2B …
```
=> [DOPS-917] Introduction of makefile build-docker target

service/api/server.go, service/perf/metrics.go, service/service.go
Nothing fancy, just enabling the metrics and debug endpoints.
https://mattermost.atlassian.net/browse/MM-43397
=> [MM-43397] Enable metrics endpoints

.github/workflows/ci-build-push.yml, Makefile
We introduce a Github Actions pipeline, to build and push rtcd artifacts.
This is a temporary measure, until we template  & finalize our build and release process to unblock the development
Ticket: https://mattermost.atlassian.net/browse/DOPS-975
=> [DOPS-975] Github action to build & push rtcd artifacts

service/perf/metrics.go, service/rtc/metrics.go, service/rtc/session.go, service/rtc/sfu.go
Adding a new `rtcd_rtc_errors_total` counter to the exposed metrics. 
/cc @stafot 
https://mattermost.atlassian.net/browse/MM-43583
=> [MM-43583] Implement RTC errors counter

service/client.go, service/client_msg.go, service/client_test.go, service/config.go, service/helper_test.go, service/option.go, service/service.go
PR adds basic reconnection support to the `rtcd` client. 
https://mattermost.atlassian.net/browse/MM-43508
=> [MM-43508] Implement basic reconnection support for rtcd client

Makefile
This introduces the following improvements: 
- [fix] Linting docker cmd alias for go-lint https://github.com/mattermost/rtcd/pull/26/commits/e58c16dbe17c36d544476ba456b21d3eee6bd3c7
- [feat] Makefile addition of docker-sign and docker-verify https://github.com/mattermost/rtcd/commit/a12541c109a5510b8537b4e05c808ac09cd8bb0a
- [feat] Makefile addition of go-fmt https://github.com/mattermost/rtcd/commit/c71a2cefbdbd77ec8639c6ab581fd0e3bdd5ba72
- [feat] Makefile build for FreeBSD😈https://github.com/mattermost/rtcd/commit/83e0f19b985ea36ead1f242133737c91c0d68331
- [feat] Makefile addition of verbosity control https://github.com/mattermost/rtcd/commit/7f2d7452ba6e7d8ad2374669315099de4c82d86f
> Setting `VERBOSE=1` will increase the verbosity. Otherwise make is mostly silent. 
> Example:
```
❯ …
```
=> [DOPS-908] Makefile improvements

build/Dockerfile
- Introducing coreutils package, to have better compatibility with GNU Utils
- Fixing make command to build
- Introducing GO_BUILD_PLATFORMS ARG to build against
=> [fix] Dockerfile build cmd, and enchancements

Makefile
Makefile Essential improvements 
- [feat] Makefile tag latest when building from master (protected branch) 
- [feat] Makefile extract GO_VERSION from go.mod 
- [fix] Makefile disable volume mounts for cosign commands 
- [fix] No need to perform go-mod-check on lint
- [chore] makefile expose GOLANG as LDFLAG
Review by commit is recommended
=> Makefile Essential improvements 

Makefile
fix introduced on the Docker_Registry assigment variable
=> [fix] fix introduced on the Docker_Registry assigment

Makefile
We add a login step for github-release target.
=> [fix] Makefile github-release login step addition

Makefile
Makefile release step variable fix
=> [fix] Makefile release step variable fix

Makefile
=> [fix] makefile fixes

Makefile
=> [fix] makefile release step

Makefile
We are changing the logic that the APP_VERSION variable is being generated.
Specifically:
- If we run under a protected_branch, we use `protected_branch_name-sha` as APP_VERSION
- If we run under a semver tag, we also push `latest` tag
Signed-off-by: Akis Maziotis <akis.maziotis@mattermost.com>
=> [feat] Makefile release taging refactor

Makefile
Building on https://github.com/mattermost/rtcd/pull/53
We are also signing and verifying the `latest` tag.
=> [fix] Makefile make sure we also sign/verify latest

Makefile
We are adding abstractions for the following targets: 
```
make release                        to build and release artifacts
make package                        to build, package and push the artifact to a container registry
make sign                           to sign the artifact and perform verification
```
=> [feat] Add target abstractions for release,package,sign

Makefile
=> [fix] Makefile APP_VERSION bug

service/rtc/config.go, service/rtc/config_test.go
Fixes #64 
https://mattermost.atlassian.net/browse/MM-45966
=> [MM-45966] Allow secure ICE server URIs

README.md, config/config.sample.toml
Documenting config settings plus some useful info in the README.
=> Document configuration settings

README.md, docs/getting_started.md
Wrote a quick guide on how to get started with Calls + `rtcd`.
@cpoile Would you be able to give it a quick try on your end as I fear there may be something to adapt in case of Mac users as the docker IPs may be different, not sure.
=> Getting started guide

docs/getting_started.md
=> Fix broken config link

docs/getting_started.md
Updating the docs as per https://github.com/mattermost/mattermost-plugin-calls/pull/186
https://mattermost.atlassian.net/browse/MM-46918
=> [MM-46918] Update docs

service/rtc/call.go, service/rtc/server.go, service/rtc/session.go, service/rtc/sfu.go
PR implements glare-free negotiation using the proposed scheme in https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation (impolite peer case).
https://github.com/mattermost/mattermost-plugin-calls/pull/276
https://mattermost.atlassian.net/browse/MM-46048
=> [MM-46048] Implement glare-free negotiation

service/ws/server.go, service/ws/server_test.go
PR fixes a potential race condition leading to a panic when shutting down the service.
https://mattermost.atlassian.net/browse/MM-49980
=> [MM-49980] Fix race condition on shutdown

service/rtc/sfu.go
It's possible that `vadMonitor.PushAudioLevel()` and `vadMonitor.Reset()` get called concurrently so we should call them under lock.
=> Fix racy access to vadMonitor

config/config.sample.toml, service/rtc/server.go
Fixes https://github.com/mattermost/mattermost-plugin-calls/issues/432
https://mattermost.atlassian.net/browse/MM-52813
=> [MM-52813] Fix using 0.0.0.0 as catch all address

Makefile
Add safe.directory for `/app` folder within docker execution https://github.com/mattermost/delivery-platform/actions/runs/5347821664/jobs/9696951014
=> hotfix: Add safe directory for in docker execution

service/rtc/sfu.go
PR allows to instruct connections to skip the DTLS hello verify phase when the `RTCD_RTC_DTLS_INSECURE_SKIP_HELLOVERIFY` environment variable is set to `true`.
https://mattermost.atlassian.net/browse/MM-52321
=> [MM-52321] Allow skipping DTLS hello verify phase

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile, client/client.go, client/client_test.go, client/rtc.go, client/websocket.go, cmd/rtcd/config_test.go, go.mod, service/auth/service.go, service/auth/session_cache_test.go, service/client_test.go, service/config.go, service/helper_test.go, service/rtc/multi_conn.go, service/rtc/multi_conn_test.go, service/rtc/net.go, service/rtc/sfu.go, service/rtc/utils.go, service/rtc/vad/vad_test.go, service/ws/client_test.go, service/ws/server.go, service/ws/server_test.go
PR reviews and improves our linting. I updated both Golang (dot release) and `golangci-lint` in the process.
=> [MM-57571] Improve linting

.github/workflows/ci.yml, .github/workflows/golangci-lint.yml, .golangci.yml, Makefile, client/helper_test.go, go.mod, go.sum
Updating Golang runtime to v1.22. Also taking the chance to update the linter and the CI actions.
https://mattermost.atlassian.net/browse/MM-60187
=> [MM-60187] Update Golang to v1.22

service/rtc/sfu.go
Yeah, it's a very small thing, but during debugging [I used ChatGPT](https://chatgpt.com/c/67632931-d520-800b-b3a1-b658ac921b48) to quickly decode the RTP packets, which was useful since it would have taken me a few more minutes to code something.
So, this little thing caused transcriber jobs to fail at https://github.com/mattermost/mattermost-plugin-calls/pull/928.
Since the packets have no payload we can safely ignore any padding since it will get stripped by the pion layer.
I spent 1h+ working on an integration test, but it's very tricky to trigger since we don't have access to the lower level, and pion (since it's bugged) will fail to unmarshal these packets on the rtcd side, before we can get them to the receiving side and check for error. 
Having our e2e tests pipeline green again …
=> [MM-62310] Fix handling of empty RTP payloads with padding
