config/config.sample.toml
service/auth.go
service/auth/crypto.go
service/auth/service.go
service/auth/service_test.go
service/auth_test.go
service/client.go
service/client_msg.go
service/client_msg_test.go
service/client_test.go
service/config.go
service/config_test.go
service/helper_test.go
service/rtc/msg.go
service/rtc/server.go
service/rtc/session.go
service/rtc/session_test.go
service/rtc/sfu.go
service/service.go
service/ws/client.go
service/ws/conn.go
service/ws/msg.go
service/ws/server.go
service/ws/server_test.go

This is the last piece of implementation that lets Calls plugin instances successfully interface with the service over network.
PR implements a `service.Client` to use the provided HTTP/WebSocket API.
Bear in mind that the sole purpose of this PR is establishing main functionality (getting calls to work). There isn't any real improvement (e.g. reconnection support) just yet. Also, APIs are very likely to break for some time still as we are trying to come up with a proper solution on the security front.
Companion PR is https://github.com/mattermost/mattermost-plugin-calls/pull/41

Service implementation

---

cmd/rtcd/config.go
cmd/rtcd/config_test.go

Letting the service use defaults if the config file is missing. This makes the service run even if not provided with a config file and removes the necessity of including such file in the docker image.
https://mattermost.atlassian.net/browse/MM-43391

[MM-43391] Use defaults if config file is missing

---

Makefile
cmd/rtcd/config.go
cmd/rtcd/config_test.go
cmd/rtcd/main.go
config/config.sample.toml
docs/env_config.md
scripts/env_config.go
service/config.go
service/helper_test.go
service/service.go

PR simplifies the configuration by removing an unnecessary level of nesting. This means the logger is now created by the service itself which I think it's acceptable.
As a bonus I've added a new `make doc` command to generate a [list of environment config overrides](https://github.com/mattermost/rtcd/blob/MM-43394/docs/env_config.md). Ideally I'd like to improve it and also document each config setting using tags but that requires far more effort so I am happy to have something rather than nothing for the time being.
https://mattermost.atlassian.net/browse/MM-43394
/cc @phoinixgrr

[MM-43394] Document config environment overrides

---

service/rtc/sfu.go
service/service.go
service/ws/conn.go
service/ws/server.go
service/ws/server_test.go

Addressing two issues that were found during initial performance testing.
- Making `rtc.Server.InitSession()` partially synchronous to avoid a race condition in which events could be processed before the connection they targeted was fully initiated in the state.
- Adding a map to the service to keep track of which MM instance the end users connections (session ids) belong to. This is to avoid WebRTC negotiation errors caused by out of order delivery of websocket messages.

High concurrency fixes

---

.gitignore
Makefile
build/Dockerfile

This is a first proposal, on Makefile refactoring introducing the following improvements:
- Decoupling of Makefile Variables from actual targets
- Easy to develop locally, not requiring binaries on the actual dev machine (docker)
- Better makefile logging
- Dockerfile linting
- Auto generated Makefile help command
- Security improvements with the introduction of SBOM and Vulnerabilities reporting. Moreover `docker run` runs as a non privileged user
- Documentation with inline commenting
- Aims to be easily portable to other Mattermost Repositories
```bash
❯ make                                                                          
Usage:
make help                           to get help
make lint                           to lint all
make test                           to test all
make …
```

[DOPS-942] Makefile refactor

---

service/audit.go
service/auth.go
service/ws/client_test.go
service/ws/server.go
service/ws/server_test.go

PR adds some additional logs to HTTP requests requiring authorization. 
Currently logging more or less everything the request gives us. Happy to make any needed change/addition.
Example log:
```
debug [2022-04-29 16:30:40.860 +02:00] registerClient caller="service/audit.go:33" remoteAddr="192.168.1.108:42846" method=POST url=/register header=map[Accept:[*/*] Content-Length:[31] Content-Type:[application/x-www-form-urlencoded] User-Agent:[curl/7.68.0]] host="172.17.0.1:8045" code=400 error="registration failed: already registered" clientID=localPluginAAAA status=fail
```
https://mattermost.atlassian.net/browse/MM-43330

[MM-43330] Log audit info on http requests

---

service/rtc/server.go

I was looking into adding a runtime platform check but it will make the initialization code unnecessarily more complex so opting for logging a warning instead of failing. 
@cpoile Let me know if this is enough to get it working on your end otherwise I'll go with a different approach.

Avoid failure if setting UDP buffer sizes errors

---

config/config.sample.toml
docs/env_config.md
service/rtc/config.go
service/rtc/server.go
service/rtc/stun.go

We are moving to this side the STUN logic to figure out an instance's own public IP address which will trigger only in case the `ICEHostOverride` is empty and ICE servers are provided.
This is especially helpful for Cloud operations now that we have simplified the networking design, with pods having public IP addresses.
Big thanks to @angeloskyratzakos for quickly validating that this approach can work.
https://mattermost.atlassian.net/browse/MM-44062

[MM-44062] Use STUN to find public IP

---

Makefile

No need to run go-build before docker-build. Build happens within the Dockerfile
https://github.com/mattermost/rtcd/blob/master/build/Dockerfile#L13

[fix] Makefile no need to run go-build before docker-build

---

docs/security.md
service/auth.go
service/auth/crypto_test.go
service/auth/service.go
service/auth/service_test.go
service/auth_test.go
service/client.go
service/client_test.go
service/random/crypto.go
service/random/crypto_test.go

PR changes the registration flow from server-generated to client-provided key. This lets us simplify quite a lot on the plugin (client) side especially in preparation to supporting multiple rtcd servers at once.
The client-provided auth key will use the same generation function so that we guarantee the same length/entropy.

Change registration flow to require client provided auth key

---

service/rtc/sfu.go

At some point we stopped passing ice servers (e.g. STUN urls) to the peer connection which meant server reflexive candidates were no longer generated. This is perfectly fine given we expect direct connectivity to be possible through the configured UDP port but if that's not the case there's still a chance things could work through the `srflx` candidate. 
This is likely what caused [this issue](https://github.com/mattermost/mattermost-plugin-calls/issues/73).
https://mattermost.atlassian.net/browse/MM-44322

[MM-44322] Pass configured ICEServers to peer connection

---

Makefile

- adding verbosity control for docker-login target
- removing unneeded `-n` option from echo
```
-n    Do not print the trailing newline character.  This may also be achieved by appending ‘\c’ to the end of the string, as is
done by iBCS2 compatible systems.  Note that this option as well as the effect of ‘\c’ are implementation-defined in IEEE Std
1003.1-2001 (“POSIX.1”) as amended by Cor. 1-2002.  Applications aiming for maximum portability are strongly encouraged to
use printf(1) to suppress the newline character.
```

[fix] makefile docker-login

---

Makefile

This fixes the docker-sign target.
Cosign binary, was escaped and did not run inside the cosign dedicated container.
Moreover, we need the cosign key variable to be exposed in the container as a file.
Therefore we mount the required volumes

[fix] Makefile docker-sign

---

Makefile

This fixes the `docker-verify` target which is affected by the same bug as described https://github.com/mattermost/rtcd/pull/40 
Cosign binary, was escaped and did not run inside the cosign dedicated container.

[fix] Makefile docker-verify

---

Makefile
build/Dockerfile

- **Makefile:** Migrating `go-test` target, to running under a container, thus decoupling from local system
- **Makefile:** Dynamically extracting and using Go Version from go.mod file
- **Dockerfile**: Using `golang:1.17` instead of `golang:1.17-alpine` for `builder` stage. Thus removing the dependency of maintaining a list of packages. 
Dockerfile step: 
```
RUN apk add \
coreutils=9.0-r2 \
make=4.3-r0 \
git=2.34.2-r0 \
--no-cache
```

[feat] Makefile go-test refactor

---

Makefile

We are fixing the logic to extract the APP_VERSION.
Specifically, we are checking if we are in protected branch, if yes use we use `latest` as app version.
Else we are checking if we are in a release tag, if yes we are using tag as app version
Else we use `dev-sha` as app version

[fix] makefile app_version logic

---

service/rtc/server.go
service/rtc/server_test.go
service/rtc/sfu.go

We make stopping the RTC server a blocking operation so that we make sure to drain the instance and exit only when all call sessions are done. 
/cc @angeloskyratzakos 
https://mattermost.atlassian.net/browse/MM-44897

[MM-44897] Add draining wait on RTC server stop

---

Makefile

Some essential fixes after getting some feedback from the calls Team cc: @streamer45  @cpoile  💯 
Review by commit is recommended: 
1. [ [feat] Makefile APP_VERSION assigment revisit](https://github.com/mattermost/rtcd/commit/b6e89e345e6443c6e90cc155b20a6d9971cedac1)
There maybe requirment to set `APP_VERSION` at CI time.
For example if tagging from protected branch to release, then this will happen:
```
`if [ $PROTECTED_BRANCH = $CURRENT_BRANCH ];`
```
setting  ```APP_VERSION=$PROTECTED_BRANCH-$APP_COMMIT```
In that case, we want to overwrite the `APP_VERSION` to be equal to the tag name.
Therefore we are changing the variable assignment to "?=" to be able to cover that case
2. [[fix] Makefile redirect git describe tags stderr output to …

Makefile essential fixes 

---

Makefile

If we run under protected branch, tag `master` instead of `master-sha`
In that way, the latest master will be available in the dev dockerhub repository

[fix] Makefile, tagging master instead of master-sha

---

docs/env_config.md
logger/logger.go
service/rtc/config.go
service/rtc/config_test.go
service/rtc/server.go
service/rtc/sfu.go
service/rtc/stun.go

Changing `ServerConfig.ICEServers` to be a list of proper ICE server config, potentially supporting TURN servers as well, which need credentials.
**Note**
This is a breaking change but it's one we can afford to make on this side. I've also added a backwards compatible unmarshaler for the config so that we can still support the previous format, just in case.
https://mattermost.atlassian.net/browse/MM-44486

[MM-44486] Use proper ICE server configs

---

service/client.go
service/ws/client.go
service/ws/server.go

It took a while to debug this cause it wasn't clear at which level the problem was happening (client vs mattermost server vs plugin vs rtcd). Initial inspection of the logs at the various levels indicated that some clients failed to receive websocket events related to voice tracks which resulted in them not hearing some unmuted participants. In fact, when someone unmutes we loop through all connections to broadcast the necessary events that eventually get the voice track to the client.
There were around 130 participants in COM yesterday. One of those unmuting caused 130 track events to get sent down a channel of buffer 64 which wasn't able to handle them all in time and got full. Eventually messages for about 4/5 users were dropped. 
Finding an ideal value is a hard problem of course and …

[MM-45150] Fix failing to add tracks due to full channel

---

config/config.sample.toml
docs/env_config.md
service/config.go
service/rtc/config.go
service/rtc/config_test.go
service/rtc/sfu.go
service/rtc/turn.go
service/rtc/turn_test.go

Adding support for generating short-lived TURN credentials as described in https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00#section-2.2
https://github.com/mattermost/mattermost-plugin-calls/pull/116
https://mattermost.atlassian.net/browse/MM-45001

[MM-45001] Add support for generating short-lived TURN credentials

---

service/client_msg.go
service/rtc/sfu.go
service/service.go

On this side it's pretty simple as it boils down to updating the connections map so that further messages will be sent to the right node.
Unrelated, but caught during testing, this also fixes a potential leak in case of initialing signaling timeout.
https://github.com/mattermost/mattermost-plugin-calls/pull/145
https://mattermost.atlassian.net/browse/MM-43838

[MM-43838] WebSocket reconnection support

---

service/rtc/server.go

MultiConn was being incorrectly initialized inside a loop.
This created repeated listener goroutines of the same connection.

service/rtc: Fixing repeat initialization of connection

---

service/client_msg.go
service/service.go

Adding a new client event that gets sent whenever a connection is closed to allow the plugin side to efficiently deinitialize any related resources. 
https://github.com/mattermost/mattermost-plugin-calls/pull/155
https://mattermost.atlassian.net/browse/MM-46124

[MM-46124] Send message on RTC connection close

---

service/auth.go
service/auth_test.go
service/client_test.go
service/helper_test.go
service/version_test.go

(just cutting and pasting the description of the problem from the channel 😄  ) :
- If client [self registration](https://github.com/mattermost/rtcd/blob/dded04f0cc2daee07ba58104c87f1422e493a0f9/config/config.sample.toml#L13) is enabled then a client can unregister itself. Right now an authenticated client can unregister any other client just by knowing their id.
- If self registration is disabled and an [admin key](https://github.com/mattermost/rtcd/blob/dded04f0cc2daee07ba58104c87f1422e493a0f9/config/config.sample.toml#L19-L21) is configured then that can unregister anyone.
- If none of the above is set (self register disabled and no admin configured) then the call should simply return forbidden.
- https://mattermost.atlassian.net/browse/MM-47231

MM-47231 - Secure the /unregister api path

---

service/rtc/call.go
service/rtc/server.go
service/rtc/session.go
service/rtc/sfu.go
service/rtc/utils.go

Quite a bit happening here which I'll try to explain. First of all the main change is an overall review of voice tracks handling which led to a significant simplification of how we deal with them. 
**Problem**
Calling `rtpSender.ReplaceTrack(nil)` on the server (pion) side is not working consistently across browsers after a new negotiation happens. For example, given a call with two participants, this sequence would trigger the issue:
1. A and B join the call (order of join doesn't matter here).
2. B unmutes
3. B mutes
4. B shares screen (sharing screen is just an example, it could be any other negotiation, like some other participant unmuting for the first time).
5. B unmutes
6. A is not hearing B
It seems like Firefox is handling this better, in fact I couldn't reproduce this on that …

[MM-47933] Simplify handling of voice tracks

---

cmd/rtcd/config.go
cmd/rtcd/config_test.go

While testing I noticed that upgrading `rtcd` could easily fail after new config settings are added (e.g. https://github.com/mattermost/rtcd/pull/75) because we are not enforcing defaults and the missing new setting would cause the service to fail. 
Setting defaults prior to loading the config file should help to avoid breaking changes while upgrading.
https://mattermost.atlassian.net/browse/MM-48952

[MM-48952] Set config defaults before attempting to load from config file

---

service/client.go
service/client_test.go
service/version.go
service/version_test.go

PR implements a `GetVersionInfo()` client API method to be used by the plugin side to implement minimum version compatibility checks.
https://github.com/mattermost/mattermost-plugin-calls/pull/287
https://mattermost.atlassian.net/browse/MM-49022

[MM-49022] Implement GetVersionInfo client API method

---

service/audit.go
service/store/bitcask.go

PR fixes a couple of potential data races:
1. Cloning HTTP requests headers to avoid reading (logging) and writing at the same time.
2. Although the underlying `bitcask` store is already safe for concurrent use, the way we use it is not since we force a sync on every write.

Fix potential data races

---

config/config.sample.toml
docs/env_config.md
service/rtc/config.go
service/rtc/config_test.go
service/rtc/server.go

PR adds a new `ice_address_udp` to optionally specify an IP address to use when listening for UDP packets.
https://github.com/mattermost/mattermost-plugin-calls/pull/293
https://mattermost.atlassian.net/browse/MM-49004

[MM-49004] Allow UDP listening address to be specified in config

---

service/client_msg.go
service/rtc/msg.go
service/rtc/server.go
service/rtc/session.go
service/rtc/sfu.go
service/rtc/vad/vad.go
service/rtc/vad/vad_test.go
service/service.go

It's been a while since I wanted to try this. PR implements server side voice activity detection. This is achieved by reading audio levels coming from clients through the special [`ssrc-audio-level`](https://www.rfc-editor.org/rfc/rfc6464) RTP header extension.
The main benefits of this approach are:
1. It avoids the performance hit needed by the client-side VAD implementation.
2. It should make mobile VAD work without additional changes.
3. The logic feels a bit more robust now. I am using standard deviation of sampled audio levels to figure out voice vs background noise. It may need some further tuning as I couldn't test it on too many systems but it's working decently well so far.
https://github.com/mattermost/mattermost-plugin-calls/pull/285 …

[MM-49236] Implement server side VAD

---

go.mod
go.sum
service/auth/service.go
service/client.go
service/client_test.go

PR adds some rate limiting to avoid the number of concurrent CPU heavy auth operations (mostly hashing) that could bring the instance to a halt if many clients connected concurrently.
I tried my best to come up with a sensible value (20 requests per second per CPU available) through some quick benchmarking but it may need more time to properly tune this.
https://mattermost.atlassian.net/browse/MM-49998

[MM-49998] Implement rate litiming on CPU heavy auth operations

---

service/rtc/call.go
service/rtc/session.go

We were locking on the call mutex but failed to lock at the session level when reading/setting the `screenTrackSender`.

Fix race condition accessing session

---

service/rtc/net.go
service/rtc/server.go
service/rtc/sfu.go
service/rtc/stun.go
service/rtc/utils.go
service/rtc/utils_test.go

After changes in https://github.com/mattermost/rtcd/pull/92 there was an issue preventing connectivity under certain scenarios as  local (to the rtcd host) candidates could get dropped due to mapping to the same public IP (e.g. ice host override). The solution is to generate a set of `remoteIP/localIP` pairs and pass them down the pion stack.
Right now we are simply mapping the first available interface to the matching public IP and everything else to its own local IP if matching to the same public one. This fixes the connectivity issues I mentioned above as it lets candidates pass deduplication but it's not perfect especially since the first interface is usually the loopback one (e.g. 127.0.0.1). We could add a specific rule to avoid mapping this to a public address but I am a bit wary …

Improve local/external IPs mapping when listening on multiple interfaces

---

service/rtc/simulcast.go

The `default` case would cause us to loop continuously causing a huge CPU resource leak.

Fix CPU leak

---

service/perf/metrics.go
service/rtc/call.go
service/rtc/metrics.go
service/rtc/session.go
service/rtc/sfu.go
service/rtc/utils.go

A race condition on join could cause tracks to be added more than once. This was spotted while I was reviewing some of the Prometheus metrics hence this PR includes those changes as well. In particular:
- Removed `rtp_packets_total` and `rtp_bytes_total`.
- They caused a [ridiculous number of allocations](https://gist.github.com/streamer45/c6c098e3c0fb5057494054b9dd1642f3) as increment calls were called in a very tight loop.
- They were not that useful to begin with since ultimately it's more important to track actual network rates.
- With simulcast enabled, they were not going to be accurate any longer since tracks can be selectively added or removed based on clients' network capacity.
- Added `rtp_tracks_total` to keep count of input/output tracks and their type.
- This is of particular …

[MM-51861] Fix race condition with adding tracks on join

---

go.mod
go.sum
service/rtc/multi_conn.go
service/rtc/session.go
service/rtc/sfu.go
service/rtc/simulcast.go

The introduction of simulcast support in https://github.com/mattermost/rtcd/pull/90 caused the peak performance at scale, measured as CPU usage, to drop by roughly 50%. This was almost exclusively due to the bandwidth estimation and congestion control logic that was added to support the new functionality.
An extensive series of load-tests was conducted to try and identify any new bottlenecks. This and the related PR (where most performance related changes live) include a number of optimizations aimed at reducing overall CPU load at scale.
Note: currently using a temporary branch to keep the diff clean as this is based on top of both `MM-50288` and `MM-51861`.
The load-test input parameters were the following:
- 25 concurrent calls
- 25 participants/call
- 2 unmuted participants/call
- 25 …

Performance optimizations

---

go.mod
go.sum
service/rtc/multi_conn.go
service/rtc/rate.go
service/rtc/rate_test.go
service/rtc/session.go
service/rtc/sfu.go
service/rtc/simulcast.go

Adding some small improvements to the simulcast logic as I have been testing it more today. Most notable changes are:
- Added an additional check on average loss to determine whether to go ahead with the level change check. Essentially if there's no loss we don't want to downgrade, regardless of the estimated rate. Ideally this shouldn't be needed as the rate from the estimator should already account for that but especially with Firefox the rates are all over the place at times, resulting in a lot of downgrades under optimal network conditions.
- Improved source rate calculation. Also now using different sample sizes based on the simulcast level as samples for higher rate tracks will be much more frequent so we don't need as many for an accurate result.
Plan is to keep testing this for a …

[MM-50288] Simulcast improvements

---

service/rtc/session.go

The simplification introduced in https://github.com/mattermost/rtcd/pull/97 meant that on join we are queuing all the tracks before actually adding them. This means that if there are more tracks (e.g. participants that unmuted at least once throughout the call) than the capacity of the channel we'd fail to add some. 
https://mattermost.atlassian.net/browse/MM-52650

[MM-52650] Bump tracks channel size

---

service/rtc/call.go
service/rtc/session.go

PR fixes an issue that could cause duplicate senders to exist in case of simulcast track which would eventually lead to SEGFAULT crash upon screen sharing stopping. The flow causing this issue was roughly the following, assuming two clients (one receiver and one presenter):
1. Both presenter and receiver join the call.
2. Presenter starts screen sharing.
3. Server receives the low quality track first and [sends it to the receiver](https://github.com/mattermost/rtcd/blob/de7d3899ad4c6efbd2beeef3e3eb679187dcde58/service/rtc/sfu.go#LL470C1-L470C1).
4. Track is added and [screen sender is set in receiver's session](https://github.com/mattermost/rtcd/blob/de7d3899ad4c6efbd2beeef3e3eb679187dcde58/service/rtc/session.go#L336).
5. The bandwidth estimation kicks in and after a couple of seconds …

[MM-53172] Fix duplicate simulcast sender

---

service/rtc/simulcast.go

I noticed a very aggressive level downgrade behaviour during the dev meeting today. Essentially the high quality track was getting replaced less than a second after being added under optimal network conditions. 
Turns out the [rate diff check](https://github.com/mattermost/rtcd/blob/de7d3899ad4c6efbd2beeef3e3eb679187dcde58/service/rtc/simulcast.go#L110) was causing this since after upgrading [we set the rate to the actual source rate](https://github.com/mattermost/rtcd/blob/de7d3899ad4c6efbd2beeef3e3eb679187dcde58/service/rtc/simulcast.go#L121-L125) but this could actually be lower than the previously estimated rates. To fix this we need to update the cached values with the new rate we are setting.
https://mattermost.atlassian.net/browse/MM-53182

[MM-53182] Fix potential improper rate check in simulcast logic

---

.gitlab-ci.yml

- Remove gitlab-ci configuration in favor of Github Actions
- Release pipeline will exist on our https://github.com/mattermost/delivery-platform repo
- Release pipeline will be triggered upon tag push . Related sensor [here](https://github.com/mattermost/delivery-platform/blob/master/automations/rtcd/release.yaml)
Related PR: https://github.com/mattermost/delivery-platform/pull/6 
https://mattermost.atlassian.net/browse/CLD-3881

feat: Migrate release pipeline to GHA

---

Makefile

- Make Makefile inputs overridable
- Switch to dockerhub image for gh cli

hotfix: Makefile inputs and proper gh-cli image

---

service/auth.go
service/auth/service.go
service/client_test.go
service/rtc/server.go

Full context of the on-going investigation is on the attached JIRA ticket. As things stand I don't think there's an issue on the application side. That said, I think the value we used to limit the concurrency of key hashing operations was a bit overly optimistic. I conducted a batch of bechmarks and tuned the value down so that at most (on average) it will consume around 80% of CPU time.
I also looked into whether we could make the hashing operation quicker but it doesn't seem a particularly clever idea to mess with the `bcrypt` cost (see https://wildlyinaccurate.com/bcrypt-choosing-a-work-factor/).
At the end of the day the problem is that this service is not really designed to be hit by hundreds of registration requests at once, something that happens on Cloud for two reasons:
1. We …

[MM-53483] Tune authentication concurrency to avoid excessive CPU usage

---

service/rtc/call.go
service/rtc/server.go
service/rtc/sfu.go

In https://github.com/mattermost/rtcd/pull/107 I had a good thought of returning an error if a `screenTrackSender` was getting overwritten. The only problem was that it didn't prevent a panic from happening next time we tried to remove a `nil` track.
PR makes sure of two things:
1. (panic fix) If removing a track fails, we check whether that's because it was a `nil` track and we only extract its ID if that's not the case.
2. (functionality fix) When a session suddenly drops without sending the expected events (e.g. `ScreenOffMessage`) we are now properly removing the track from the receivers who are left and clearing `screenTrackSender` so that next time someone attempts to share it won't be failing.
https://mattermost.atlassian.net/browse/MM-53511

[MM-53511] Properly remove screen sharing tracks if sender suddenly drops

---

service/rtc/logger.go
service/rtc/sfu.go

We were missing potentially useful warnings from our logs that would ease debugging issues. Given Pion has an easy way to pass a proper logger we wrap our existing one so that everything can get printed out nicely.
```
info  [2023-07-25 16:09:31.866 -06:00] peer connection state changed: connected      caller="rtc/logger.go:70" origin="webrtc/v3.(*PeerConnection).onConnectionStateChange webrtc/peerconnection.go:495"
warn  [2023-07-25 16:09:31.867 -06:00] test warning                                  caller="rtc/logger.go:78" origin="webrtc/v3.(*PeerConnection).undeclaredMediaProcessor webrtc/peerconnection.go:1627"
error [2023-07-25 16:09:31.867 -06:00] test error                                    caller="rtc/logger.go:86" origin="webrtc/v3.(*PeerConnection).undeclaredMediaProcessor …
```

Improve logging

---

service/rtc/sfu.go

I wasn't able to reproduce this so not sure this addition will have any effect but until we get more logs (https://github.com/mattermost/rtcd/pull/116) it's hard to say what's going on. 
There's no clear indication that we are leaking anything on our side assuming that closing the peer connection would be enough to release all its resources.
https://mattermost.atlassian.net/browse/MM-53807

[MM-53807] Explicitly stop receiver on exit

---

service/rtc/call.go
service/rtc/sfu.go
service/rtc/utils.go
service/rtc/utils_test.go

Looking at metrics on Community I spotted something a little disturbing. Our counter for output video (screen) tracks went negative. 
Inspecting the logs revealed an unusual track being removed when the session closed:
My theory so far is that the track is created internally by `pion` as a result of the client negotiating a `sendrecv` transceiver.  To avoid this sort of issues, before decreasing the counter we are adding a track ID validation function that will only match tracks explicitly created by us.

Don't decrease counter for internal/unused tracks

---

go.mod
go.sum

Updating a dependency that was breaking the build when using the new Golang v1.21

Fix broken dependency

---

service/perf/metrics.go
service/rtc/call.go
service/rtc/metrics.go
service/rtc/session.go
service/rtc/sfu.go

I rarely had to group by `callID` in practice and it was also causing lots of redundant metrics potentially affecting performance on installations making use of calls in many channels. I think we are good without it.
https://mattermost.atlassian.net/browse/MM-54445

[MM-54445] Remove CallID label from metrics

---

service/rtc/server.go
service/rtc/server_test.go

Fixing a potential deadlock in tests. I mostly had to raise some channel sizes and rework the way we were queuing messages.
There's quite a bit of concurrency involved so can't be 100% certain the flakyness is completely gone but at least we should now be failing with timeout rather than deadlocking.
https://mattermost.atlassian.net/browse/MM-54767

[MM-54767] Fix potential deadlock in rtc test

---

service/rtc/server_test.go
service/rtc/session.go
service/rtc/sfu.go

Fixing this on our side for expediency. This race could cause a `panic` when stopping the server as closing the peer connection didn't guarantee for the `OnICECandidate` handler to be done so we'd go ahead and close the `receiveCh` which could still be written into, leading to a crash. 
I believe the race was introduced after the recent dependency upgrade, more specifically by https://github.com/pion/ice/commit/898746c1f52f0371579cf0720aacfd620a76c63b
I'll still see if I can send a patch upstream as I believe this sort of cases should be dealt with by the underlying API, essentially guaranteeing that after closing the `ice.Agent` no goroutines created by it would still be running.
https://mattermost.atlassian.net/browse/MM-55415

[MM-55415] Fix race condition on stop

---

.github/workflows/ci.yml
.github/workflows/golangci-lint.yml
Makefile
build/Dockerfile
go.mod
go.sum

Bumping Golang dependency to 1.21. Also bumping a few more things on CI (e.g. golangci-lint, node version used for building the plugin for e2e tests)

Bump Go to 1.21

---

client/client.go
client/websocket.go

PR implements a handler for the new `job_stop` websocket event in the Calls client.
https://mattermost.atlassian.net/browse/MM-56187

[MM-56187] Handle wsEventJobStop

---

config/config.sample.toml
docs/env_config.md
service/rtc/config.go
service/rtc/config_test.go
service/rtc/sfu.go

PR implements a new config setting to optionally override the port used to form the ICE host candidates. This can be useful in scenarios where there are more network components in front of rtcd that may not necessarily share the port throughout the stack.
A concrete example would be a load balancer (NLB or nginx) listening on more client accessible ports like 80 or 443 and forwarding the traffic to `rtcd` which internally listens to non privileged ports.
https://mattermost.atlassian.net/browse/MM-46676

[MM-46676] Implement config option to override ICE candidates port

---

Makefile
build/test/docker-compose.yaml
build/test/prepare-plugin.sh
client/client_test.go
client/helper_test.go
client/rtc_test.go
client/websocket_test.go
go.mod
go.sum

Bumping the `github.com/grafana/pyroscope-go/godeltaprof` dependency as it's currently breaking `golangci-lint` on Go 1.22+

Fix linting on newer versions

---

client/call.go
client/client.go
client/rtc.go
client/types.go
client/websocket.go

- Add a client.Send function
- WIP -- needs tests
- https://mattermost.atlassian.net/browse/MM-56540

MM-56540 - Live Captions: add client.Send

---

client/api.go
client/api_test.go
client/client.go
client/client_test.go
client/helper_test.go
client/rtc.go
client/rtc_test.go
client/websocket.go
client/websocket_test.go

PR implements some of the core functionalities we were missing from `rtcd.Client`. This effectively becomes the official (and public) Golang implementation for a Mattermost Calls capable client.
https://mattermost.atlassian.net/browse/MM-57843

[MM-57843] Add more API functionalities to client implementation

---

client/api.go
client/api_test.go

I was trying to follow what a real (browser) client would do but it looks like it's a bit bugged. As long as we pause writing on the track we should be fine.

Avoid replacing track on mute

---

go.mod
service/client.go
service/client_test.go
service/service.go
service/system.go
service/system_test.go
service/ws/client.go

PR implements a new `/system` API endpoint to return information on system load to be used by the plugin side to do smarter load balancing of new calls. 
https://mattermost.atlassian.net/browse/MM-58085

[MM-58085] Implement system info API endpoint

---

config/config.sample.toml
docs/env_config.md
service/rtc/config.go
service/rtc/config_test.go
service/rtc/server.go
service/rtc/server_test.go
service/rtc/sfu.go
service/rtc/utils.go
service/rtc/utils_test.go

PR adds support for a more advanced syntax in the `rtc.ice_host_port_override` config setting which takes the following form:
`localIPA/externalPortA,localIPB/externalPortB`
This becomes useful in deployments that are exposing a single public IP address and hence must be using different port numbers to map against multiple rtcd services listening internally. 
The reason to pass a full mapping is to make it possible to deploy in Kubernetes where the config passed must be the same across all the pods in the deployment. Each rtcd instance will only use the port override that maps to its local IP.
/cc @coltoneshaw 
https://mattermost.atlassian.net/browse/MM-58136

[MM-58136] Support advanced mapping for ice host port override

---

service/rtc/utils.go
service/rtc/utils_test.go

A small (but potentially significant) fix on https://github.com/mattermost/rtcd/pull/137.
We shouldn't override the port for local addresses as they could appear in the map (mapped to themselves) which is a valid case.

[MM-58136] Don't use port override for local addresses

---

service/rtc/server_test.go
service/rtc/sfu.go
service/rtc/utils.go
service/rtc/utils_test.go

Covering another case which we'll need to unblock https://mattermost.atlassian.net/browse/CLD-7443. The port override should also apply to public addresses found through STUN since they effectively become host overrides.

[MM-58136] Apply port override to public addresses found through STUN

---

service/rtc/call.go
service/rtc/session.go
service/rtc/sfu.go
service/rtc/utils.go

Initial ceiling tests identified a bottleneck when writing screen tracks in large calls (> 250 participants). This is because the write loop runs on a single goroutine since we use a single output track. This results in the CPU not being utilized to the fullest and packets getting significantly delayed or even dropped. 
To overcome the current limitation, this PR proposes to create N output tracks and concurrently write to them. 
These changes are showing to improve overall performance and CPU utilization on our target instance (`c7i.xlarge`) by a factor of ~2.5, getting us from around 300 participants to 800 per call with near-zero packet loss.
https://mattermost.atlassian.net/browse/MM-54335

[MM-54335] Improve write concurrency for screen tracks

---

service/rtc/net.go
service/service.go

- This fixes two issues on mac:
- the `failed to set udp receive buffer` and `failed to set udp send buffer` warnings on startup.
- the `failed to get cpu stat` error every second once it's started.
- Since we don't support mac, don't set udp buffers for mac, don't start the stat polling, and return a 404 on the system endpoint when it's mac (the plugin will use the random fallback).
- For the curious: For the snd_buf and rcvbuf, it looks like mac's max socket buf is 8mb, that's why it's failing. You can't increase that unless you increase the mbuf clusters, and you can't do that (I tried) without booting into recovery mode and disabling security settings. For stat, Mac doesn't have /proc/stat, it has sysctl.
- Tests don't need to be changed, since they're run on a linux container. Would …

Prevent log warnings and errors for mac

---

Makefile
build/Dockerfile

Adding support for building and releasing multi-arch Docker images (`amd64` and `arm64`).
https://mattermost.atlassian.net/browse/MM-57029

[MM-57029] Multi-arch Docker images

---

Makefile
build/Dockerfile

I forgot to remove the redundant push step, which is causing the release pipeline to fail. The images are already published automatically by the building process.

[MM-57029] Remove redundant push step

---

client/api_test.go
go.mod
go.sum
service/client_test.go
service/rtc/session.go
service/rtc/sfu.go
service/version.go
service/version_test.go

Looking at goroutines profiles highlighted a couple of (unrelated) issues:
1. Some read calls on incoming voice tracks can suddenly block due to an apparent regression upstream (`pion/transport`). 	  	
- This is still under investigation. Downgrading to the previous version is enough to prevent the issue while a fix is found.
2. The `CloseSession` could get stuck indefinitely in case of a timeout during the initial signaling phase due to a circular check on the session's done channel.
- Reworked the function to preemptively close the channel in these fail-early cases.
https://mattermost.atlassian.net/browse/MM-59548

[MM-59548] Fix potentially stuck goroutines

---

client/api.go
client/api_test.go
client/call.go
client/client.go
client/config.go
client/helper_test.go
client/types.go

PR adds AV1 support to the client implementation. This will make it possible to use this new functionality in the load-test client.

Add AV1 support to client implementation

---

client/api.go
client/api_test.go
client/client.go
client/helper_test.go
client/rtc.go
client/websocket.go
service/rtc/call.go
service/rtc/session.go

Sending keyframes can be expensive for the presenter, as it requires more bandwidth. It gets worse when N receivers concurrently ask for a keyframe. This is common when a presenter begins screen sharing in a large call.
PR introduces some rate limiting to avoid forwarding more than 1 PLI (picture loss indication) request per second.
https://mattermost.atlassian.net/browse/MM-60189

[MM-60189] Rate limit forwarding PLI requests

---

client/client.go
client/config.go
client/helper_test.go
client/rtc.go
client/rtc_monitor.go
client/rtc_monitor_test.go
service/perf/metrics.go
service/rtc/dc/msg.go
service/rtc/metrics.go
service/rtc/server.go

PR adds support for receiving and tracking basic client metrics (round trip time, jitter and loss rate). These can then be easily surfaced through our existing Prometheus/Grafana stack (see screenshot).
I also added a basic Golang client implementation, however it's not very accurate given some limitations in the pion implementation (jitter is especially problematic). We are keeping these off by default so that we don't get wild reports from transcriber or other clients we may have in production.
https://github.com/mattermost/calls-common/pull/41
https://mattermost.atlassian.net/browse/MM-60561

[MM-60561] RTC client metrics

---

service/perf/metrics.go

PR reviews the buckets for our histograms since the [default ones](https://github.com/prometheus/client_golang/blob/05fcde9fe4eb93d3fb7b56ebe51acf80536f0583/prometheus/histogram.go#L265C28-L265C64) didn't make too much sense with the range of values we'd expect. For example, range for loss rate is between 0 and 1 so we don't need further buckets.
The same goes for latency values such as round-trip times that we cap at 1 second because past that it's almost pointless to track as the app would be unusable.

Review histograms buckets

---

config/config.sample.toml
docs/env_config.md
service/config.go
service/helper_test.go
service/rtc/config.go
service/rtc/config_test.go
service/rtc/net.go
service/rtc/net_test.go
service/rtc/server.go
service/rtc/server_test.go

We implement a new `UDPSocketsCounts` config setting to control the number of UDP listening sockets created per local address. This is particularly helpful in case the RTCServer is embedded in the plugin, which could easily cause file descriptor exhaustion. The default value for rtcd standalone isn't changing (numCPU * 100). 
https://mattermost.atlassian.net/browse/MM-61786

[MM-61786] Add config setting to control udp sockets count

---

client/rtc.go

> EnableSCTPZeroChecksum controls the zero checksum feature in SCTP. This removes the need to checksum every incoming/outgoing packet and will reduce latency and CPU usage.

Enable SCTP optimization on client side

---

service/client.go
service/client_test.go
service/config.go
service/rtc/server.go
service/service.go
service/session.go

PR implements a new `/calls/{callID}/sessions/{sessionID}` HTTP API endpoint to let clients access information about a specific session (its config). This will enable the plugin side to know whether a session exists and help deal with potential inconsistencies (e.g., stuck calls).
https://mattermost.atlassian.net/browse/MM-62410

[MM-62410] Implement API handler to fetch session config

---

build/test/docker-compose.yaml

Updating the testing pipelines to use the new version.
Relates to https://github.com/mattermost/mattermost/pull/30039

Bump Postgres to v13

---

Makefile
go.mod

Bumping the Golang version used to build. 
https://mattermost.atlassian.net/browse/MM-63296

[MM-63296] Bump Golang version to v1.23.6

---

config/config.sample.toml
service/rtc/config.go
service/rtc/config_test.go
service/rtc/server.go
service/rtc/sfu.go

Even when listening on specific interfaces (i.e., through the `ice_address_udp` and `ice_address_tcp` settings), the ICE layer would generate candidates for all available local addresses. This is problematic for a few reasons, but mostly because we wouldn't listen to all of those IPs. We add the necessary changes to filter out anything we are not going to listen to.
https://mattermost.atlassian.net/browse/MM-64239

[MM-64239] Filter out candidates for unused local addresses
